package hanium.oldercare.oldercareservice.handlermessage;

public enum DeviceMessage {

    REFRESH_DONE, REFRESH_DEVICE_READAPT, REFRESH_DEVICE_COMP, CHECK_DEVICE_BIND_DONE, CREDENTIAL_SUCCEED, CREDENTIAL_FAIL,
    EDIT_PROFILE_SUCCEED, EDIT_PROFILE_FAIL, EDIT_PASSWORD_SUCCEED, EDIT_PASSWORD_FAIL, EDIT_PASSWORD_NOT_MATCH,

}
